sudo: required
services:
  - docker

before_install:
  - docker build -t sonxurxo/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sonxurxo/docker-react npm run test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "DockerReact-env-1"
  bucket_name: "elasticbeanstalk-eu-central-1-873912740737"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"