sudo: required
services:
  - docker

before_install:
  - docker build -t sonxurxo/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sonxurxo/docker-react npm run test -- --watchAll=false

